# Generated by Django 5.1.1 on 2024-10-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0009_alter_joke_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jokes', to='jokes.tag'),
        ),
    ]
